export const SECTION_KEYS = [
  "identity_snapshot",
  "numerology_core",
  "astrology_cosmology",
  "location_analysis",
  "current_city_analysis",
  "soulmate_timing",
  "red_flags_patterns",
  "shadow_work",
  "self_improvement",
  "love_languages",
  "career_money",
  "hobbies_lifestyle",
  "fitness_psychology",
  "fashion_system",
  "shopping_links",
  "music_frequency",
  "spotify_pack",
  "film_tv_profile",
  "seven_day_plan",
  "thirty_day_plan",
  "three_year_arc",
  "holistic_blueprint",
] as const;

export type SectionKey = (typeof SECTION_KEYS)[number];

export interface SectionMeta {
  key: SectionKey;
  title: string;
  description: string;
  icon: string;
  requiredInputs: string[];
  optionalInputs: string[];
  premiumOnly: boolean;
  unlockLevel: number;
  estimatedTokens: number;
  dependencies: SectionKey[];
}

export const SECTION_REGISTRY: Record<SectionKey, SectionMeta> = {
  identity_snapshot: {
    key: "identity_snapshot",
    title: "Identity Snapshot",
    description: "Your core traits, strengths, friction points, and growth edge",
    icon: "User",
    requiredInputs: ["firstName", "dob", "birthCity", "birthCountry"],
    optionalInputs: ["middleName", "lastName", "birthTime"],
    premiumOnly: false,
    unlockLevel: 1,
    estimatedTokens: 800,
    dependencies: [],
  },
  numerology_core: {
    key: "numerology_core",
    title: "Numerology Core",
    description: "Life Path, Expression, Soul Urge, and all core numbers with full math",
    icon: "Hash",
    requiredInputs: ["firstName", "dob"],
    optionalInputs: ["middleName", "lastName"],
    premiumOnly: false,
    unlockLevel: 1,
    estimatedTokens: 1200,
    dependencies: [],
  },
  astrology_cosmology: {
    key: "astrology_cosmology",
    title: "Astrology & Cosmology Themes",
    description: "Sun sign, decan, elements, planetary themes, and symbolic energy map",
    icon: "Star",
    requiredInputs: ["dob"],
    optionalInputs: ["birthTime", "birthCity"],
    premiumOnly: false,
    unlockLevel: 1,
    estimatedTokens: 1000,
    dependencies: [],
  },
  location_analysis: {
    key: "location_analysis",
    title: "Location Analysis",
    description: "City recommendations across California, USA, and worldwide",
    icon: "MapPin",
    requiredInputs: ["dob", "birthCity", "birthCountry"],
    optionalInputs: ["currentCity", "goals"],
    premiumOnly: false,
    unlockLevel: 3,
    estimatedTokens: 1500,
    dependencies: ["identity_snapshot"],
  },
  current_city_analysis: {
    key: "current_city_analysis",
    title: "Current City Analysis",
    description: "Assessment of your current location's ceiling, growth potential, and timing",
    icon: "Building",
    requiredInputs: ["currentCity"],
    optionalInputs: ["careerField", "relationshipStatus"],
    premiumOnly: false,
    unlockLevel: 3,
    estimatedTokens: 800,
    dependencies: [],
  },
  soulmate_timing: {
    key: "soulmate_timing",
    title: "Soulmate Timing & Compatibility",
    description: "Love windows, archetypes, best matches, and relationship progression",
    icon: "Heart",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["birthTime", "relationshipStatus", "currentCity"],
    premiumOnly: false,
    unlockLevel: 2,
    estimatedTokens: 1200,
    dependencies: ["numerology_core"],
  },
  red_flags_patterns: {
    key: "red_flags_patterns",
    title: "Red Flags & Patterns",
    description: "Relationship patterns, triggers, self-sabotage loops, and constructive replacements",
    icon: "AlertTriangle",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["relationshipStatus"],
    premiumOnly: true,
    unlockLevel: 4,
    estimatedTokens: 1000,
    dependencies: ["identity_snapshot"],
  },
  shadow_work: {
    key: "shadow_work",
    title: "Shadow Work & Healing",
    description: "CBT-based pattern loops, cognitive distortions, boundary scripts, and 30-day plan",
    icon: "Moon",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["goals"],
    premiumOnly: true,
    unlockLevel: 3,
    estimatedTokens: 2000,
    dependencies: ["identity_snapshot"],
  },
  self_improvement: {
    key: "self_improvement",
    title: "Self-Improvement Roadmap",
    description: "Emotional upgrades, habits, boundaries, and step-by-step growth path",
    icon: "TrendingUp",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["goals", "careerField"],
    premiumOnly: true,
    unlockLevel: 3,
    estimatedTokens: 1200,
    dependencies: ["identity_snapshot"],
  },
  love_languages: {
    key: "love_languages",
    title: "Love Languages",
    description: "Ranked love languages with personalized guidance",
    icon: "HeartHandshake",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["relationshipStatus"],
    premiumOnly: true,
    unlockLevel: 4,
    estimatedTokens: 600,
    dependencies: ["identity_snapshot"],
  },
  career_money: {
    key: "career_money",
    title: "Career & Money",
    description: "Work style, strength stack, high-fit roles, money psychology, and execution plan",
    icon: "Briefcase",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["careerField", "budgetRange"],
    premiumOnly: true,
    unlockLevel: 3,
    estimatedTokens: 1500,
    dependencies: ["identity_snapshot", "numerology_core"],
  },
  hobbies_lifestyle: {
    key: "hobbies_lifestyle",
    title: "Hobbies & Lifestyle",
    description: "Creative, social, skill-based hobbies, sports, and leisure recommendations",
    icon: "Palette",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["goals", "stylePreference"],
    premiumOnly: true,
    unlockLevel: 3,
    estimatedTokens: 800,
    dependencies: ["identity_snapshot"],
  },
  fitness_psychology: {
    key: "fitness_psychology",
    title: "Fitness Psychology",
    description: "Consistency plan, motivation style, 4-day template, and 12-week progression",
    icon: "Dumbbell",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["goals"],
    premiumOnly: true,
    unlockLevel: 3,
    estimatedTokens: 1000,
    dependencies: ["identity_snapshot"],
  },
  fashion_system: {
    key: "fashion_system",
    title: "Fashion System",
    description: "Style archetype, color palette with hex codes, capsule wardrobe, and outfits",
    icon: "Shirt",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["stylePreference", "budgetRange"],
    premiumOnly: true,
    unlockLevel: 4,
    estimatedTokens: 1000,
    dependencies: ["identity_snapshot"],
  },
  shopping_links: {
    key: "shopping_links",
    title: "Shopping Links",
    description: "Value and premium tier shopping suggestions with search phrases",
    icon: "ShoppingBag",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["stylePreference", "budgetRange"],
    premiumOnly: true,
    unlockLevel: 4,
    estimatedTokens: 600,
    dependencies: ["fashion_system"],
  },
  music_frequency: {
    key: "music_frequency",
    title: "Music & Frequency Guide",
    description: "Brainwave states, frequency pairings, and personalized music expansion",
    icon: "Music",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["musicPreference"],
    premiumOnly: true,
    unlockLevel: 4,
    estimatedTokens: 800,
    dependencies: [],
  },
  spotify_pack: {
    key: "spotify_pack",
    title: "Spotify Pack",
    description: "10 curated tracks for focus, calm, mood lift, and sleep",
    icon: "Headphones",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["musicPreference"],
    premiumOnly: true,
    unlockLevel: 4,
    estimatedTokens: 600,
    dependencies: ["music_frequency"],
  },
  film_tv_profile: {
    key: "film_tv_profile",
    title: "Film & TV Profile",
    description: "Taste profile with personalized film and show recommendations",
    icon: "Film",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: [],
    premiumOnly: true,
    unlockLevel: 4,
    estimatedTokens: 600,
    dependencies: ["identity_snapshot"],
  },
  seven_day_plan: {
    key: "seven_day_plan",
    title: "7-Day Starter Plan",
    description: "Daily micro-actions to kickstart your growth journey",
    icon: "Calendar",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["goals"],
    premiumOnly: false,
    unlockLevel: 1,
    estimatedTokens: 600,
    dependencies: ["identity_snapshot"],
  },
  thirty_day_plan: {
    key: "thirty_day_plan",
    title: "30-Day Plan",
    description: "Four-week structured plan: awareness, replacement, experiments, consolidation",
    icon: "CalendarRange",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["goals"],
    premiumOnly: true,
    unlockLevel: 5,
    estimatedTokens: 1200,
    dependencies: ["identity_snapshot", "self_improvement"],
  },
  three_year_arc: {
    key: "three_year_arc",
    title: "3-Year Strategic Arc",
    description: "Year-by-year focus for career, love, money, identity, and expansion",
    icon: "Rocket",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["careerField", "currentCity", "goals"],
    premiumOnly: true,
    unlockLevel: 5,
    estimatedTokens: 1500,
    dependencies: ["identity_snapshot", "career_money"],
  },
  holistic_blueprint: {
    key: "holistic_blueprint",
    title: "Holistic Life Blueprint",
    description: "Complete summary with needs, blockers, healing moves, and future direction",
    icon: "Compass",
    requiredInputs: ["dob", "firstName"],
    optionalInputs: ["goals", "currentCity", "careerField"],
    premiumOnly: true,
    unlockLevel: 5,
    estimatedTokens: 1000,
    dependencies: ["identity_snapshot", "numerology_core"],
  },
};
