interface ExportSection {
  section_key: string;
  title: string;
  summary: string;
  assumptions: string[];
  limits: string[];
  details: Record<string, unknown>;
  actions: string[];
  scores: Record<string, number>;
  ui_blocks: Array<{
    type: string;
    content?: unknown;
    label?: string;
    items?: string[];
    value?: number;
    max?: number;
    headers?: string[];
    rows?: string[][];
    expression?: string;
    title?: string;
    body?: string;
    author?: string;
    level?: number;
  }>;
}

export function exportToMarkdown(sections: ExportSection[]): string {
  const lines: string[] = ["# Destination Future Report", "", `Generated: ${new Date().toLocaleDateString()}`, ""];

  for (const section of sections) {
    lines.push(`## ${section.title}`, "");

    if (section.assumptions.length > 0) {
      lines.push("**Assumptions:**");
      section.assumptions.forEach((a) => lines.push(`- ${a}`));
      lines.push("");
    }

    if (section.limits.length > 0) {
      lines.push("**Limitations:**");
      section.limits.forEach((l) => lines.push(`- ${l}`));
      lines.push("");
    }

    if (section.summary) {
      lines.push(section.summary, "");
    }

    // Render ui_blocks to markdown
    for (const block of section.ui_blocks) {
      switch (block.type) {
        case "heading":
          lines.push(`${"#".repeat((block.level || 2) + 1)} ${block.content}`, "");
          break;
        case "paragraph":
          lines.push(`${block.content}`, "");
          break;
        case "list":
          block.items?.forEach((item) => lines.push(`- ${item}`));
          lines.push("");
          break;
        case "numbered_list":
          block.items?.forEach((item, i) => lines.push(`${i + 1}. ${item}`));
          lines.push("");
          break;
        case "score_bar":
          lines.push(`- **${block.label}:** ${block.value}/${block.max || 100}`);
          break;
        case "math":
          lines.push("```", `${block.expression}`, "```", "");
          break;
        case "quote":
          lines.push(`> ${block.content}${block.author ? ` — ${block.author}` : ""}`, "");
          break;
        case "card":
          lines.push(`### ${block.title || ""}`, block.body || "", "");
          break;
        case "table":
          if (block.headers) {
            lines.push(`| ${block.headers.join(" | ")} |`);
            lines.push(`| ${block.headers.map(() => "---").join(" | ")} |`);
          }
          block.rows?.forEach((row) => lines.push(`| ${row.join(" | ")} |`));
          lines.push("");
          break;
        case "checklist":
          block.items?.forEach((item, i) => {
            const checked = false; // Default to unchecked for export
            lines.push(`- [${checked ? "x" : " "}] ${item}`);
          });
          lines.push("");
          break;
        case "divider":
          lines.push("---", "");
          break;
      }
    }

    if (section.actions.length > 0) {
      lines.push("### Action Steps", "");
      section.actions.forEach((a) => lines.push(`- [ ] ${a}`));
      lines.push("");
    }

    if (Object.keys(section.scores).length > 0) {
      lines.push("### Scores", "");
      Object.entries(section.scores).forEach(([key, val]) => {
        const label = key.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase());
        lines.push(`- **${label}:** ${val}/100`);
      });
      lines.push("");
    }

    lines.push("---", "");
  }

  lines.push("", "*Generated by Destination Future*");
  return lines.join("\n");
}

export function exportToJson(sections: ExportSection[], meta?: Record<string, unknown>): string {
  return JSON.stringify(
    {
      exportedAt: new Date().toISOString(),
      generator: "Destination Future v0.1.0",
      meta: meta || {},
      sections,
    },
    null,
    2
  );
}

export function exportToPlainText(sections: ExportSection[]): string {
  const lines: string[] = ["DESTINATION FUTURE REPORT", `Generated: ${new Date().toLocaleDateString()}`, "", "=".repeat(50), ""];

  for (const section of sections) {
    lines.push(section.title.toUpperCase(), "-".repeat(section.title.length), "");

    if (section.summary) {
      lines.push(section.summary, "");
    }

    for (const block of section.ui_blocks) {
      switch (block.type) {
        case "heading":
          lines.push(`${block.content}`, "");
          break;
        case "paragraph":
          lines.push(`${block.content}`, "");
          break;
        case "list":
        case "checklist":
          block.items?.forEach((item) => lines.push(`  * ${item}`));
          lines.push("");
          break;
        case "numbered_list":
          block.items?.forEach((item, i) => lines.push(`  ${i + 1}. ${item}`));
          lines.push("");
          break;
        case "score_bar":
          lines.push(`  ${block.label}: ${block.value}/${block.max || 100}`);
          break;
        case "quote":
          lines.push(`  "${block.content}"${block.author ? ` — ${block.author}` : ""}`, "");
          break;
        case "math":
          lines.push(`  ${block.expression}`, "");
          break;
        case "divider":
          lines.push("-".repeat(30), "");
          break;
      }
    }

    if (section.actions.length > 0) {
      lines.push("ACTION STEPS:");
      section.actions.forEach((a, i) => lines.push(`  ${i + 1}. ${a}`));
      lines.push("");
    }

    lines.push("=".repeat(50), "");
  }

  return lines.join("\n");
}
